#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Build the packaged (fat) wheel of the fused prefill attention extension.

The manifest's one named gap: v0.3.0 had no wheel, so its ``artifacts`` block
had to record the JIT source build as the artifact and name the packaging hole
in ``limitations``. This tool closes it. What it produces is a wheel that can
answer, from its own metadata and with no repository present, the questions a
promotion record asks of a binary: which sources went in, which architectures
came out, and which toolchain built it.

Three properties are load-bearing.

**Both architectures, and never a bare ``-arch``.** The wheel carries SASS for
every registered mma.sync target -- ``sm_89`` (development tier) and
``sm_120a`` (production tier) -- generated by ``kernel.gencode_for``, the one
place in the repository that knows about claim K5: a bare ``-arch=sm_120a``
executable build silently lowers to ``sm_120`` and ptxas then rejects the
architecture-specific MMA. The flags are *derived* from each target profile's
declared compute capability and then cross-checked against the ``toolchain
.gencode`` string that profile publishes, so a profile that ever grows a bare
``-arch`` fails this build instead of shipping a wheel that cannot run.

**One Python surface.** The wheel installs a separate top-level distribution,
``attn_kernel_lab_ext``, holding the compiled module and its build info -- not a
second copy of ``attn_kernel_lab``. A wheel that shipped both would put two
copies of the loader and the contract validation on ``sys.path``, and whichever
won the import race would decide which one actually ran.

**A real, recomputable build id.** ``build_id`` is ``kernel.source_build_id()``
-- sha256 over the same canonical source set, in the same order, with the same
semantics as the JIT path reports -- so a wheel built from a given tree and that
tree's own source digest are directly comparable. The per-file digests ride
along so a mismatch can say *which* file moved.

    tools/build_wheel.py                                 # dev build -> dist/
    tools/build_wheel.py --release-id d256-int8-fp8-v0.4.0
    tools/build_wheel.py --outdir /tmp/wheels --json /tmp/wheels/build.json

Needs torch importable at build time (so ``pip`` runs with
``--no-build-isolation``) and ``nvcc`` on ``PATH``.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import pprint
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
for _path in (ROOT / "src", ROOT / "tools"):
    if str(_path) not in sys.path:
        sys.path.insert(0, str(_path))

import yaml  # noqa: E402

from attn_kernel_lab import kernel as kernel_mod  # noqa: E402
from attn_kernel_lab.capability import V1_CAPABILITY  # noqa: E402
from attn_kernel_lab.identity import package_api_version  # noqa: E402
from tree_digest import tree_digest  # noqa: E402

#: The registered mma.sync targets a packaged wheel must serve. Both, always:
#: the development tier that runs correctness locally and the production tier
#: the records qualify. Shipping only one makes the wheel unloadable on the
#: other, and the failure surfaces as a driver-level "no kernel image" long
#: after the build that caused it.
DEFAULT_TARGETS = ("sm89-rtx4090-local", "sm120-rtxpro6000-server")

#: Digest paths of the manifest's ``source.source_tree_sha256`` (v0.3.0 record).
DIGEST_PATHS = ("src", "tests/kernel")

DISTRIBUTION = "attn-kernel-lab-ext"
PACKAGE = kernel_mod.WHEEL_PACKAGE
EXT_MODULE = "_fp8_prefill_attn"

#: Version of a build that is not a published release. ``--release-id`` naming a
#: ``vX.Y.Z`` release promotes it to that version; anything else stays a dev
#: build, because a wheel that names a release it has not been qualified for is
#: exactly the artifact the pin check exists to catch.
DEV_VERSION = "0.4.0.dev0"
UNRELEASED = "unreleased"


# --------------------------------------------------------------------------
# generated package files
# --------------------------------------------------------------------------

INIT_PY = '''# SPDX-License-Identifier: Apache-2.0
"""Compiled artifact for attn-kernel-lab's fused low-precision prefill attention.

GENERATED by tools/build_wheel.py -- edit that, not this.

This package is deliberately thin, and deliberately not part of
``attn_kernel_lab``: the operator's validation, preprocessing pipeline and
loader have exactly one copy, in that package, and this distribution ships only
the binary plus the identity it was built with.

Importing it costs no torch import and no CUDA context. ``BUILD_INFO`` is a
plain Python literal, so a consumer can verify its pin -- release, variant,
source digest, architectures -- on a machine with no GPU at all, before it
commits to loading anything. The extension itself is imported only by
:func:`load_extension`, which ``attn_kernel_lab.kernel.load`` calls.
"""
from ._build_info import BUILD_INFO

__all__ = ["BUILD_INFO", "load_extension"]
__version__ = BUILD_INFO["version"]

_ext = None


def load_extension():
    """Import and return the compiled extension module.

    ``torch`` is imported first and on purpose: the extension links against
    libtorch, and importing it into a process that has not loaded torch fails
    with an undefined-symbol error that names none of that.
    """
    global _ext
    if _ext is None:
        import torch  # noqa: F401

        from . import {ext_module} as _compiled

        _ext = _compiled
    return _ext
'''

BUILD_INFO_PY = '''# SPDX-License-Identifier: Apache-2.0
"""What this artifact reports about itself. GENERATED by tools/build_wheel.py.

``build_id`` is sha256 over the canonical source set with the same semantics as
``attn_kernel_lab.kernel.source_build_id()``: the two are directly comparable,
which is what lets a test prove a wheel was built from the tree it claims.
``source_files`` carries the per-file digests so a mismatch can name the file.
"""

BUILD_INFO = {info}
'''

SETUP_PY = '''# SPDX-License-Identifier: Apache-2.0
# GENERATED by tools/build_wheel.py.
from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension

# The gencode flags are passed verbatim from the generator. torch suppresses its
# own arch flags when the caller supplies any (it scans these for "arch"), so
# this list is exactly what nvcc receives -- and it is generated by
# attn_kernel_lab.kernel.gencode_for, never hand-written (claim K5).
NVCC_FLAGS = {nvcc_flags}

setup(
    name={distribution!r},
    version={version!r},
    description="Compiled fused low-precision paged prefill attention kernel "
                "(mma.sync family) for attn-kernel-lab",
    license="Apache-2.0",
    packages=[{package!r}],
    ext_modules=[
        CUDAExtension(
            name="{package}.{ext_module}",
            sources=["csrc/fp8_prefill_attn.cu"],
            extra_compile_args={{"cxx": ["-O3"], "nvcc": NVCC_FLAGS}},
        )
    ],
    cmdclass={{"build_ext": BuildExtension}},
    python_requires=">=3.11",
    zip_safe=False,
)
'''

PYPROJECT_TOML = """# GENERATED by tools/build_wheel.py.
[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"
"""


# --------------------------------------------------------------------------
# resolution
# --------------------------------------------------------------------------


def resolve_targets(target_ids) -> list[dict]:
    """Derive the code-generation targets from the registered target profiles.

    Each profile's ``device.compute_capability`` generates the flag through
    ``kernel.gencode_for``; the profile's own ``toolchain.gencode`` string then
    has to agree. That cross-check is the point: it makes a registry that ever
    records a bare ``-arch`` (claim K5) fail the build rather than produce a
    wheel whose SASS silently lowered.
    """
    targets = []
    for target_id in target_ids:
        profile_path = ROOT / "targets" / f"{target_id}.yaml"
        if not profile_path.exists():
            raise SystemExit(f"no such target profile: {profile_path}")
        profile = yaml.safe_load(profile_path.read_text(encoding="utf-8"))
        major, minor = (int(value) for value in profile["device"]["compute_capability"])
        gencode = kernel_mod.gencode_for(major, minor)
        declared = (profile.get("toolchain") or {}).get("gencode")
        if declared and declared.strip() != gencode:
            raise SystemExit(
                f"target {target_id} declares gencode {declared!r} but its compute "
                f"capability ({major}, {minor}) generates {gencode!r}. Reconcile the "
                "profile; a bare -arch form here is claim K5 and must never ship."
            )
        targets.append(
            {
                "target": target_id,
                "capability": [major, minor],
                "arch": kernel_mod.arch_tag_for(major, minor),
                "gencode": gencode,
                "family": (profile.get("capabilities") or {}).get("implementation_family"),
            }
        )
    families = {target["family"] for target in targets}
    if families - {"mma_sync"}:
        raise SystemExit(
            f"targets span implementation families {sorted(families)}; this wheel "
            "builds the mma.sync source only (a wgmma implementation is a different "
            "artifact with its own layout_version)"
        )
    return targets


def refuse_polluted_tree() -> None:
    """Stop if an in-tree build artifact would corrupt ``source_tree_sha256``.

    Found the hard way during this tool's own verification: ``pip install .``
    leaves ``src/attn_kernel_lab.egg-info/`` behind, and ``tree_digest.py`` --
    the ONLY sanctioned producer of that field -- has no exclusion for it, so
    the digest silently stops matching a clean checkout of the same commit.
    Embedding one of those into a wheel would produce an artifact whose pin no
    reviewer could reproduce, which is worse than a failed build.
    """
    strays = sorted(
        stray
        for path in DIGEST_PATHS
        for pattern in ("*.egg-info", "*.dist-info")
        for stray in (ROOT / path).rglob(pattern)
    )
    if strays:
        listing = "\n  ".join(str(stray.relative_to(ROOT)) for stray in strays)
        raise SystemExit(
            "in-tree build artifacts would change source_tree_sha256:\n  "
            f"{listing}\nRemove them and rebuild (they are ignored by git, not "
            "by tree_digest.py)."
        )


def _git(*args: str) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(ROOT), *args],
            capture_output=True, text=True, check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return result.stdout.strip()


def _toolchain() -> dict:
    """Toolchain facts read from the build environment, never declared."""
    import torch

    from torch.utils.cpp_extension import CUDA_HOME

    if CUDA_HOME is None:
        raise SystemExit(
            "torch cannot find a CUDA toolkit (CUDA_HOME is unset and nvcc is not "
            "on PATH). Activate the lab environment before building."
        )
    nvcc = shutil.which("nvcc") or str(pathlib.Path(CUDA_HOME) / "bin" / "nvcc")
    version = subprocess.run(
        [nvcc, "--version"], capture_output=True, text=True, check=True
    ).stdout
    release = re.search(r"release ([\d.]+), V([\d.]+)", version)
    build = re.search(r"Build (\S+)", version)
    # CUDA_HOME itself is deliberately NOT recorded below: it is a path on the
    # build host, it says nothing the nvcc version string does not, and
    # BUILD_INFO ships inside the wheel.
    return {
        "cuda": torch.version.cuda,
        "nvcc": (
            f"nvcc {release.group(2)} ({build.group(1)})"
            if release and build
            else version.strip().splitlines()[-1]
        ),
        "torch": torch.__version__,
        "cxx11_abi": bool(torch._C._GLIBCXX_USE_CXX11_ABI),
    }


def _abi_tags(toolchain: dict) -> tuple[str, str]:
    """``(binary_abi, glibc_tag)`` for the interpreter and libc doing the build."""
    import platform

    python_tag = f"cp{sys.version_info.major}{sys.version_info.minor}"
    torch_version = toolchain["torch"].split("+")[0]
    cuda_tag = f"cu{(toolchain['cuda'] or '').replace('.', '')}"
    libc, libc_version = platform.libc_ver()
    return (
        f"{python_tag}-torch{torch_version}-{cuda_tag}",
        f"{libc or 'libc'}{libc_version}",
    )


def build_info(targets: list[dict], *, release_id: str, version: str,
               api_version: int) -> dict:
    """Everything the installed wheel will be able to say about itself.

    No timestamp, deliberately: a build time makes two builds of one tree differ
    byte-for-byte, and the whole point of ``build_id`` is that they should not.
    """
    refuse_polluted_tree()
    toolchain = _toolchain()
    binary_abi, glibc = _abi_tags(toolchain)
    arch_tags = [target["arch"] for target in targets]
    # "sm_120a" -> "sm120a" inside the variant id: the v0.3.0 record's
    # "jit-src-sm120a" spelling, kept so the two are read side by side.
    variant_tags = [arch.replace("_", "") for arch in arch_tags]
    source_sha, _ = tree_digest(ROOT, list(DIGEST_PATHS))
    commit = _git("rev-parse", "HEAD")
    status = _git("status", "--porcelain")
    return {
        "artifact_variant_id": "-".join([binary_abi, glibc, *variant_tags]),
        "binary_abi": binary_abi,
        "build_id": kernel_mod.source_build_id(),
        "candidate_commit": commit,
        "cuda_arch_targets": arch_tags,
        "digest_paths": list(DIGEST_PATHS),
        "dirty": bool(status) if status is not None else None,
        "distribution": DISTRIBUTION,
        "gencode_flags": [target["gencode"] for target in targets],
        "layout_version": V1_CAPABILITY.layout_version,
        "operator_contract_version": V1_CAPABILITY.operator_contract_version,
        "package_api_version": api_version,
        "release_id": release_id,
        "returns_lse": V1_CAPABILITY.returns_lse,
        "source_files": kernel_mod.source_file_digests(),
        "source_tree_sha256": source_sha,
        "targets": [
            {"target": target["target"], "capability": target["capability"]}
            for target in targets
        ],
        "toolchain": toolchain,
        "version": version,
    }


# --------------------------------------------------------------------------
# build
# --------------------------------------------------------------------------


def stage(directory: pathlib.Path, info: dict, targets: list[dict]) -> None:
    """Write the throwaway source distribution the wheel is built from."""
    package_dir = directory / PACKAGE
    package_dir.mkdir(parents=True)
    (package_dir / "__init__.py").write_text(
        INIT_PY.replace("{ext_module}", EXT_MODULE), encoding="utf-8"
    )
    (package_dir / "_build_info.py").write_text(
        BUILD_INFO_PY.format(info=pprint.pformat(info, sort_dicts=True, width=84)),
        encoding="utf-8",
    )
    (directory / "csrc").mkdir()
    shutil.copy2(
        ROOT / "src" / "attn_kernel_lab" / "csrc" / "fp8_prefill_attn.cu",
        directory / "csrc" / "fp8_prefill_attn.cu",
    )
    (directory / "setup.py").write_text(
        SETUP_PY.format(
            nvcc_flags=pprint.pformat(["-O3", *(t["gencode"] for t in targets)]),
            distribution=DISTRIBUTION,
            version=info["version"],
            package=PACKAGE,
            ext_module=EXT_MODULE,
        ),
        encoding="utf-8",
    )
    (directory / "pyproject.toml").write_text(PYPROJECT_TOML, encoding="utf-8")


def run_pip_wheel(source: pathlib.Path, outdir: pathlib.Path, verbose: bool) -> pathlib.Path:
    """Build into a private directory, then publish the one wheel it produced.

    Building straight into ``outdir`` would make "which file did this run
    produce?" a question about directory contents, and a rebuild that lands on
    an existing filename would be indistinguishable from having produced
    nothing.
    """
    outdir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="attn-kernel-lab-whl-") as staging:
        command = [
            sys.executable, "-m", "pip", "wheel",
            "--no-build-isolation", "--no-deps",
            "--wheel-dir", staging, str(source),
        ]
        print(f"$ {' '.join(command)}", flush=True)
        result = subprocess.run(
            command, text=True,
            stdout=None if verbose else subprocess.PIPE,
            stderr=subprocess.STDOUT if not verbose else None,
        )
        if result.returncode != 0:
            if result.stdout:
                print(result.stdout)
            raise SystemExit(f"pip wheel failed with exit code {result.returncode}")
        produced = sorted(pathlib.Path(staging).glob("*.whl"))
        if len(produced) != 1:
            raise SystemExit(f"expected exactly one wheel, got {produced}")
        return pathlib.Path(shutil.copy2(produced[0], outdir / produced[0].name))


def verify_arches(wheel: pathlib.Path, expected: list[str]) -> list[str]:
    """cuobjdump the wheel's compiled module; require every expected arch.

    The build-time half of claim K5. A wheel whose SASS silently lowered is
    indistinguishable from a correct one until it reaches a device that cannot
    run it, so the check belongs here, before anyone installs it.
    """
    cuobjdump = shutil.which("cuobjdump")
    if cuobjdump is None:
        print("WARNING: cuobjdump not on PATH; architecture verification SKIPPED")
        return []
    with tempfile.TemporaryDirectory() as tmp:
        with zipfile.ZipFile(wheel) as archive:
            names = [name for name in archive.namelist() if name.endswith(".so")]
            if len(names) != 1:
                raise SystemExit(f"expected exactly one .so in {wheel.name}, got {names}")
            extracted = pathlib.Path(archive.extract(names[0], tmp))
        listing = subprocess.run(
            [cuobjdump, "--list-elf", str(extracted)],
            capture_output=True, text=True, check=True,
        ).stdout
    lines = [line.strip() for line in listing.splitlines() if line.strip()]
    missing = [arch for arch in expected if not any(f".{arch}." in line for line in lines)]
    if missing:
        raise SystemExit(
            f"{wheel.name} carries no code for {missing}; cuobjdump --list-elf said:\n"
            + "\n".join(lines)
        )
    return lines


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--outdir", type=pathlib.Path, default=ROOT / "dist",
                        help="where to leave the wheel (default: dist/)")
    parser.add_argument("--target", action="append", dest="targets", default=None,
                        metavar="TARGET_ID",
                        help=f"registered target to build for; repeatable "
                             f"(default: {' '.join(DEFAULT_TARGETS)})")
    parser.add_argument("--release-id", default=UNRELEASED,
                        help="release this artifact belongs to; stays 'unreleased' "
                             "until a qualified release exists, so a pin check fails "
                             "closed against a development build")
    parser.add_argument("--version", default=None,
                        help=f"wheel version (default: derived from --release-id, "
                             f"else {DEV_VERSION})")
    parser.add_argument("--package-api-version", type=int, default=None,
                        help="override the derived package_api_version (contract §2)")
    parser.add_argument("--json", type=pathlib.Path, default=None,
                        help="also write the build summary here as JSON")
    parser.add_argument("--keep-build", action="store_true",
                        help="leave the staged build tree in place for inspection")
    parser.add_argument("--no-verify", action="store_true",
                        help="skip the cuobjdump architecture check (not recommended)")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    targets = resolve_targets(args.targets or DEFAULT_TARGETS)
    release_match = re.search(r"v(\d+\.\d+\.\d+)$", args.release_id)
    version = args.version or (release_match.group(1) if release_match else DEV_VERSION)
    api_version = (
        args.package_api_version
        if args.package_api_version is not None
        else package_api_version()
    )

    info = build_info(
        targets, release_id=args.release_id, version=version, api_version=api_version
    )
    print(f"distribution : {DISTRIBUTION} {version}")
    print(f"release_id   : {info['release_id']}")
    print(f"variant      : {info['artifact_variant_id']}")
    print(f"build_id     : {info['build_id']}")
    print(f"source tree  : {info['source_tree_sha256']} over {list(DIGEST_PATHS)}")
    print(f"gencode      : {' '.join(info['gencode_flags'])}")
    print(f"toolchain    : {info['toolchain']['nvcc']}, torch {info['toolchain']['torch']}")

    build_root = pathlib.Path(tempfile.mkdtemp(prefix="attn-kernel-lab-wheel-"))
    try:
        stage(build_root, info, targets)
        wheel = run_pip_wheel(build_root, args.outdir.resolve(), args.verbose)
    finally:
        if args.keep_build:
            print(f"build tree   : {build_root}")
        else:
            shutil.rmtree(build_root, ignore_errors=True)

    evidence = [] if args.no_verify else verify_arches(wheel, info["cuda_arch_targets"])
    summary = {
        "wheel": str(wheel),
        "wheel_sha256": hashlib.sha256(wheel.read_bytes()).hexdigest(),
        "build_info": info,
        "cuobjdump_list_elf": evidence,
    }
    print(f"\nwheel        : {wheel}")
    print(f"wheel_sha256 : {summary['wheel_sha256']}")
    for line in evidence:
        print(f"  cuobjdump  : {line}")
    if args.json:
        args.json.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n",
                             encoding="utf-8")
        print(f"summary      : {args.json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
